language: java
notifications:
  hipchat:
    rooms:
      secure: hTBiaR+J7t7zIoTwNnJhX+xJf3oX8lttM5taTtrnRbWcUBOiykKOuaOeVwlJMvKkhcSp9KBkR5z17om/egzReisGITNJK+nZBcZ2Eao8Pa5WUkLfTO2z3zgDYx3eUyl1cuAPRuYt/N2UX72FiqIsA3iBBh5oB9ucRaVK5pMFS9EvRYKbSwpw1dRAPvWB4VuzHpkSe9RiOzFhUHC2tulPqWRWd1ihT86vezOcv9k1c0XOyN4CrNKBdmsthgIjdtRpxMAdZB1BJj8ZTz1mV0jVvjH0vK5FsaNE4WuTwSqVJJLpaukCjwMn4YJlYi8u/tEqagAJ7FDF5a3Gm0yurVJMolAuYrif/H4HiSD4E15myfFCmx7tHc7ev82y2uGRvmKPsnjf584qEA78hy1XZO1LkF1gh7ZqInj/uIzgwDjHv+p4EL4oqXk4PTwUl8Tw4/jwWvEQNCGqdbHijkUDUTEFLx8FaEiR41lQNeeMCqKFzduAb9Kl1o1cG/oyyjkxgv3PbjNNNKiN8M1whVMkfTRcxdBcKghNg9JIbW4/N5iY1+/+XcXXPGfFdOMbmNobv61vbocrKngzYKzWHkw8jrmodPOWW8c7eVB8Z8sQDEl7RdglpKZSKj0s5qOJGwCOlW45A7x7437/yEAa/eC8UAibdE5iESbcEEydW8OxuIwbucw=
deploy:
  provider: releases
  api_key:
    secure: E+Ou3rPdGnQt63DfQfwGJMRTG4sY43V6UbhOg7KnHTbaGX0ey2c0p3iSj4LABkGqM4qsaAwcT9h0buLZen8/bsPHTBJiYdJfCcCu39drFxkeUWcFbUgir5Ss46h5ZRjv3MAy41StINwSgBrBjBtKaO1fO5/DQEUI+m3KF2meNQruj+/VHGerd2clBB3eNF5KHAEM/WpQOAIDoygiBiUs9UmvYY0TUMUJXpz/I5dGhqo4YcxXElSmYy+r9sZ4UsZ6owVqBV0AaXF+12nUk+GaIw3NSP7cAuuLop2eZqAIbOhQ3oVDQBljarRuIDQz+CZwyKiauctpnj9+5dHbaFB+fYeWmHFS87OYYQlrtiBKBsxn5FJyZmyz3fKhJNWh/58keA0YMyuTWLR+YiFM92T4KekIYjDB9mNe+3HI66uV3iJ69P2v1Kj8Xi/sqUdbL3ojMR8guIERueAHc1X8iytGe1BqCBTB1L6O2aXRDjSW3bIJeu7sU/vKto/zxWLjcGjTbyU/KW62QHG7zWkKAMXa+siPayFK9Eqt2Ao7V/pC/lloA25dFJtr+JwY+MYTjMeaeay8PjCG8l4TYpajDgOh1LUI3V9S2PsFrjzWqLhLAUnZv66b8VCfjYvG4phgR56ezqQLb7jlzpGl0AW+84IYWgEXSizCi1XVmPQZBTtA0hk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-remotescript-taskpassword-plugin

